server:
  port: 8761

spring:
  application:
    name: eureka-service-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#logging:
#  level:
#    com.netflix.eureka: OFF
#    com.netflix.discovery: OFF