spring:
  application:
    name: conference-service
  datasource:
    url: jdbc:mysql://localhost:3306/conference
    username: root
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect